import { Injectable } from '@angular/core';
@Injectable({
  providedIn: 'root'
})
export class ImagesService {

  constructor() { }

 Images = [
    { name: 'admiral-bobbery', img: 'Admiral Bobbery.png' },
    { name: 'antasma', img: 'Antasma.png' },
    { name: 'baby-daisy', img: 'Baby Daisy.png' },
    { name: 'baby-donkey-kong', img: 'Baby Donkey Kong.png' },
    { name: 'baby-luigi', img: 'Baby Luigi.png' },
    { name: 'baby-mario', img: 'Baby Mario.png' },
    { name: 'baby-peach', img: 'Baby Peach.png' },
    { name: 'baby-rosalina', img: 'Baby Rosalina.png' },
    { name: 'banzai-bill', img: 'Banzai bill.png' },
    { name: 'birdo', img: 'Birdo.png' },
    { name: 'blue-toad', img: 'Blue Toad.png' },
    { name: 'bob-omb', img: 'Bob-omb.png' },
    { name: 'bombette', img: 'Bombette.png' },
    { name: 'boo', img: 'Boo.png' },
    { name: 'boom-boom', img: 'Boom Boom.png' },
    { name: 'boomerang-bro', img: 'Boomerang Bro.png' },
    { name: 'bow', img: 'Bow.png' },
    { name: 'bowbow', img: 'Bowbow.png' },
    { name: 'bowser-jr', img: 'Bowser Jr.png' },
    { name: 'bowser', img: 'Bowser.png' },
    { name: 'bullet-bill', img: 'Bullet Bill.png' },
    { name: 'cackletta', img: 'Cackletta.png' },
    { name: 'cappy', img: 'Cappy.png' },
    { name: 'captain-syrup', img: 'Captain Syrup.png' },
    { name: 'captain-toad', img: 'captain toad.png' },
    { name: 'chain-chomp', img: 'Chain Chomp.png' },
    { name: 'chargin-chuck', img: 'Chargin Chuck.png' },
    { name: 'count-bleck', img: 'Count Bleck.png' },
    { name: 'cranky-kong', img: 'Cranky Kong.png' },
    { name: 'diddy-kong', img: 'Diddy Kong.png' },
    { name: 'dimentio', img: 'Dimentio.png' },
    { name: 'dixie-kong', img: 'Dixie Kong.png' },
    { name: 'donkey-kong', img: 'Donkey Kong.png' },
    { name: 'dry-bones', img: 'Dry Bones.png' },
    { name: 'dry-bowser', img: 'Dry Bowser.png' },
    { name: 'fawful', img: 'Fawful.png' },
    { name: 'fire-bro', img: 'Fire Bro.png' },
    { name: 'flurrie', img: 'Flurrie.png' },
    { name: 'foreman-spike', img: 'Foreman_Spike.png' },
    { name: 'funky-kong', img: 'Funky Kong.png' },
    { name: 'fuzzy', img: 'Fuzzy.png' },
    { name: 'geno', img: 'Geno.png' },
    { name: 'goomba', img: 'Goomba.png' },
    { name: 'goombella', img: 'Goombella.png' },
    { name: 'green-toad', img: 'Green Toad.png' },
    { name: 'hammer-bro', img: 'Hammer Bro.png' },
    { name: 'hellen-gravely', img: 'Hellen Gravely.png' },
    { name: 'huey', img: 'Huey.png' },
    { name: 'ice-bro', img: 'Ice Bro.png' },
    { name: 'iggy', img: 'Iggy.png' },
    { name: 'kamek', img: 'Kamek.png' },
    { name: 'kersti', img: 'Kersti.png' },
    { name: 'kiddy-kong', img: 'Kiddy Kong.png' },
    { name: 'king-boo-luigi', img: "King Boo (Luigi's Mansion).png" },
    { name: 'king-boo', img: 'King Boo.png' },
    { name: 'king-bob-omb', img: 'King_Bob-omb.png' },
    { name: 'koopa-troopa', img: 'KoopaTroopa.png' },
    { name: 'koops', img: 'Koops.png' },
    { name: 'lakilester', img: 'Lakilester.png' },
    { name: 'lakitu', img: 'Lakitu.png' },
    { name: 'larry-koopa', img: 'Larry Koopa.png' },
    { name: 'lemmy', img: 'Lemmy.png' },
    { name: 'lubba', img: 'Lubba.png' },
    { name: 'ludwig', img: 'Ludwig.png' },
    { name: 'luigi', img: 'Luigi.png' },
    { name: 'luma', img: 'Luma.png' },
    { name: 'mallow', img: 'Mallow.png' },
    { name: 'mario', img: 'Mario.png' },
    { name: 'mcballyhoo', img: 'MCBallyhoo.png' },
    { name: 'mecha-koopa', img: 'MechaKoopa.png' },
    { name: 'metal-mario', img: 'Metal Mario.png' },
    { name: 'monty-mole', img: 'Monty Mole.png' },
    { name: 'morton', img: 'Morton.png' },
    { name: 'ms-mowz', img: 'Ms Mowz.png' },
    { name: 'nabbit', img: 'Nabbit.png' },
    { name: 'olivia', img: 'Olivia.png' },
    { name: 'origami-king', img: 'Origami King.png' },
    { name: 'parakarry', img: 'Parakarry.png' },
    { name: 'paratroopart', img: 'Paratroopart.png' },
    { name: 'pauline', img: 'Pauline.png' },
    { name: 'peachette', img: 'Peachette.png' },
    { name: 'petey-piranha', img: 'Petey Piranha.png' },
    { name: 'pink-gold-peach', img: 'PinkGoldPeach.png' },
    { name: 'piranha-plant', img: 'PiranhaPlant.png' },
    { name: 'pokey', img: 'Pokey.png' },
    { name: 'polari', img: 'Polari.png' },
    { name: 'polterpup', img: 'Polterpup.png' },
    { name: 'pom-pom', img: 'Pom Pom.png' },
    { name: 'princess-daisy', img: 'Princess Daisy.png' },
    { name: 'princess-peach', img: 'Princess Peach.png' },
    { name: 'prof-e-gadd', img: 'Prof E. Gadd.png' },
    { name: 'purple-toad', img: 'Purple Toad.png' },
    { name: 'queen-bee', img: 'QueenBee.png' },
    { name: 'reznor', img: 'Reznor.png' },
    { name: 'rosaline', img: 'Rosaline.png' },
    { name: 'roy', img: 'Roy.png' },
    { name: 'shadow-mario', img: 'Shadow Mario.png' },
    { name: 'shy-guy', img: 'Shy Guy.png' },
    { name: 'smithy', img: 'Smithy.png' },
    { name: 'spike', img: 'Spike.png' },
    { name: 'spiny', img: 'Spiny.png' },
    { name: 'spookum', img: 'Spookum.png' },
    { name: 'sprixie-princess', img: 'Sprixie princess.png' },
    { name: 'stanley', img: 'Stanley.png' },
    { name: 'starlow', img: 'Starlow.png' },
    { name: 'sushie', img: 'Sushie.png' },
    { name: 'tatanga', img: 'Tatanga.png' },
    { name: 'thwomp', img: 'Thwomp.png' },
    { name: 'toad', img: 'Toad.png' },
    { name: 'toadette', img: 'Toadette.png' },
    { name: 'toadsworth', img: 'Toadsworth.png' },
    { name: 'toady', img: 'Toady.png' },
    { name: 'vivian', img: 'Vivian.png' },
    { name: 'waluigi', img: 'Waluigi.png' },
    { name: 'wario', img: 'Wario.png' },
    { name: 'watt', img: 'Watt.png' },
    { name: 'wendy', img: 'Wendy.png' },
    { name: 'wiggler', img: 'Wiggler.png' },
    { name: 'yellow-toad', img: 'Yellow Toad.png' },
    { name: 'yoshi', img: 'Yoshi.png' }
  ]
}